eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

connection:
  info:
    postgres:
      user: test
      pass: password
    rabbitmq:
      user: test
      pass: password
      
gearlaunch:
  vendor:
    wrapper:
      poweredBy: ${POWERED_BY|Powered by GearLaunch}