spring:
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      database: "vendor-timberline-prod"
            
vendor:
  affiliateId: "CT_productionId"
  ordersSubmissionUrl: "http://api.production.co-timber.com/v16/submit"
  ordersQueryUrl: "http://api.production.co-timber.com/api/orders/{orderId}/status?affiliate={affiliateId}"
  submissionDelay: 30000 # DB polling delay for posting to Vendor API (milliseconds)
  
gearlaunch:
  mailhost: "PRODUCTION.mail.timberline.gearlaunch.com"