server:
  port: ${SERVER_PORT:8201}
  
spring:
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      database: "vendor-timberline"
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS: false
    serialization-inclusion: NON_NULL

vendor:
  affiliateId: "CT_0030954"
  ordersSubmissionUrl: "http://api.staging.co-timber.com/v15/submit"
  ordersQueryUrl: "http://api.staging.co-timber.com/api/orders/{orderId}/status?affiliate={affiliateId}"
  submissionDelay: 30000 # DB polling delay for posting to Vendor API (milliseconds)
  
gearlaunch:
  mailhost: "TEST.mail.timberline.gearlaunch.com"